on:
  pull_request:

jobs:
  pre-commit:
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@DD-833
    with:
      python-version: "3.10.2"

  pytest:
    uses: agblox/github-reusable-workflows/.github/workflows/pytest.yml@DD-833
    with:
      python-version: "3.10.2"

  commitlint:
    uses: agblox/github-reusable-workflows/.github/workflows/commitlint.yml@DD-833

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
      - pytest
    uses: agblox/github-reusable-workflows/.github/workflows/approve.yml@DD-833
    secrets:
      token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}
