on:
  pull_request:

jobs:
  pre-commit:
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@v2.0.2

  pytest:
    uses: agblox/github-reusable-workflows/.github/workflows/pytest.yml@v2.0.2

  commitlint:
    uses: agblox/github-reusable-workflows/.github/workflows/commitlint.yml@v2.0.2

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
      - pytest
    uses: agblox/github-reusable-workflows/.github/workflows/approve.yml@v2.0.2
    secrets:
      token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}
