on:
  pull_request:

jobs:
  pre-commit:
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@v1.0.6
    with:
      python-version: "3.10"

  pytest:
    uses: agblox/github-reusable-workflows/.github/workflows/pytest.yml@v1.0.6
    with:
      python-version: "3.10"

  commitlint:
    uses: agblox/github-reusable-workflows/.github/workflows/commitlint.yml@v1.0.6

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
      - pytest
    uses: agblox/github-reusable-workflows/.github/workflows/approve.yml@v1.0.6
    secrets:
      token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}
