on:
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Create globally available pre-commit cache
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@v2.0.4

  pytest:
    name: Create globally available poetry cache
    uses: agblox/github-reusable-workflows/.github/workflows/pytest.yml@v2.0.4
    with:
      run-unit: false

  release:
    uses: agblox/github-reusable-workflows/.github/workflows/release-workflow.yml@v2.0.4
    secrets:
      token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}

  slack-workflow-status:
    if: ${{ failure() }}
    needs:
      - release
    uses: agblox/github-reusable-workflows/.github/workflows/status-to-slack.yml@v2.0.4
    secrets:
      slack-webhook: ${{ secrets.GIT_SLACK_WEBHOOK }}
