on:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit and update globally available pre-commit cache
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}

  slack-workflow-status:
    if: ${{ failure() }}
    name: Post Workflow Status To Slack
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
    - uses: Gamesight/slack-workflow-status@master
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        slack_webhook_url: ${{secrets.TEMPLATE_APPLICATION_SLACK_WEBHOOK}}
