on:
  push:
    branches:
      - master  # globally available cache https://stackoverflow.com/a/66632107/4249707
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry
      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true
      - name: Set up poetry cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            .venv
            /home/runner/nltk_data
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make bootstrap
      - name: Run pytest
        run: make tests
